# Generated by Django 4.2 on 2024-08-05 19:44

from django.db import migrations, models
import guitars.validation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, validators=[guitars.validation.validar_cedula])),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, validators=[guitars.validation.validar_correo])),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
