# Generated by Django 5.1 on 2024-08-15 21:06

import django.db.models.deletion
import guitars.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, validators=[guitars.validation.validar_cedula])),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, validators=[guitars.validation.validar_correo])),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=10, unique=True)),
                ('brand', models.CharField(max_length=45)),
                ('model', models.CharField(max_length=45)),
                ('color', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Guitarras Clasicas', 'Guitarras Clasicas'), ('Guitarras Acusticas', 'Guitarras Acusticas'), ('Bajos', 'Bajos'), ('Guitarras Electricas', 'Guitarras Electricas'), ('Guitarras Electro Acusticas', 'Guitarras Electro Acusticas')], max_length=45)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_selling', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('picture', models.ImageField(upload_to='guitars_images')),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitars.client')),
                ('product', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='guitars.product')),
            ],
        ),
    ]
