# Generated by Django 5.1 on 2024-08-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Guitarras Electricas', 'Guitarras Electricas'), ('Guitarras Clasicas', 'Guitarras Clasicas'), ('Bajos', 'Bajos'), ('Guitarras Electro Acusticas', 'Guitarras Electro Acusticas'), ('Guitarras Acusticas', 'Guitarras Acusticas')], max_length=45),
        ),
    ]
