# Generated by Django 4.2 on 2024-08-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bajos', 'Bajos'), ('Guitarras Electro Acusticas', 'Guitarras Electro Acusticas'), ('Guitarras Electricas', 'Guitarras Electricas'), ('Guitarras Acusticas', 'Guitarras Acusticas'), ('Guitarras Clasicas', 'Guitarras Clasicas')], max_length=45),
        ),
    ]
