# Generated by Django 4.2 on 2024-08-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0002_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='total_amount',
            new_name='total',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Guitarras Electricas', 'Guitarras Electricas'), ('Bajos', 'Bajos'), ('Guitarras Clasicas', 'Guitarras Clasicas'), ('Guitarras Acusticas', 'Guitarras Acusticas'), ('Guitarras Electro Acusticas', 'Guitarras Electro Acusticas')], max_length=45),
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
