# Generated by Django 5.1 on 2024-08-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Guitarras Acusticas', 'Guitarras Acusticas'), ('Guitarras Electro Acusticas', 'Guitarras Electro Acusticas'), ('Guitarras Clasicas', 'Guitarras Clasicas'), ('Bajos', 'Bajos'), ('Guitarras Electricas', 'Guitarras Electricas')], max_length=45),
        ),
    ]
