# Generated by Django 4.2 on 2024-08-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Guitarras Electro Acusticas', 'Guitarras Electro Acusticas'), ('Guitarras Acusticas', 'Guitarras Acusticas'), ('Guitarras Clasicas', 'Guitarras Clasicas'), ('Guitarras Electricas', 'Guitarras Electricas'), ('Bajos', 'Bajos')], max_length=45),
        ),
    ]
