# Generated by Django 4.2 on 2024-08-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Guitarras Electricas', 'Guitarras Electricas'), ('Guitarras Acusticas', 'Guitarras Acusticas'), ('Bajos', 'Bajos'), ('Guitarras Clasicas', 'Guitarras Clasicas'), ('Guitarras Electro Acusticas', 'Guitarras Electro Acusticas')], max_length=45),
        ),
    ]
