# Generated by Django 5.1 on 2024-08-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Guitarras Clasicas', 'Guitarras Clasicas'), ('Guitarras Electricas', 'Guitarras Electricas'), ('Guitarras Electro Acusticas', 'Guitarras Electro Acusticas'), ('Bajos', 'Bajos'), ('Guitarras Acusticas', 'Guitarras Acusticas')], max_length=45),
        ),
    ]
