# Generated by Django 5.1 on 2024-08-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
<<<<<<< HEAD
            field=models.CharField(choices=[('Bajos', 'Bajos'), ('Guitarras Clasicas', 'Guitarras Clasicas'), ('Guitarras Acusticas', 'Guitarras Acusticas'), ('Guitarras Electricas', 'Guitarras Electricas'), ('Guitarras Electro Acusticas', 'Guitarras Electro Acusticas')], max_length=45),
=======
            field=models.CharField(choices=[('Guitarras Electro Acusticas', 'Guitarras Electro Acusticas'), ('Guitarras Clasicas', 'Guitarras Clasicas'), ('Guitarras Electricas', 'Guitarras Electricas'), ('Guitarras Acusticas', 'Guitarras Acusticas'), ('Bajos', 'Bajos')], max_length=45),
>>>>>>> 2a023c397cf5ca732e4d5412cb63d598acccaf63
        ),
    ]
